### ISSUE TITLE
what the difference between with the Official

### ISSUE THREAD

**Issue by bau720123** [appfeel/connectivity-monitor-cordova#3]
hi @appfeel 

what the difference between with the Official
https://github.com/apache/cordova-plugin-network-information/blob/df7aac845dc7deddbdb76e89216776a802ee8b67/doc/index.md

thanks

**Comment by appfeel** [comment]
Hi @bau720123 
it provides connectivity class as an extra layer so it can be used both by other plugins and by cordova apps, as it's the case of https://github.com/appfeel/admob-google-cordova

At the beginning it was just a class for com.admob.google plugin that later was converted to a plugin itself :)

thanks
