### ISSUE TITLE
onReachabilityChanged event never called

### ISSUE THREAD

**Issue by zigzag-way** [appfeel/connectivity-monitor-cordova#6]
I used the adapted sample code but onReachabilityChanged never called...

**Comment by siddiq** [comment]
This project doesn't seems active.

**Comment by miqmago** [comment]
Well this is a dependency for `cordova-admob`, it's intention was never to be used as itself, but we can take a look on it.

**Comment by miqmago** [comment]
Which platform are you using? Also there was a typo in the example, see https://github.com/appfeel/connectivity-monitor-cordova/pull/7

**Comment by goliatone** [comment]
@miqmago does this library actually work? I have not managed to get an actual event when toggling WiFi on/off

**Comment by miqmago** [comment]
It was working with ios 9, haven't tested in ios 10. Don't have plans to test it in near future. If you can debug it in XCode, contributions are really welcome.

**Comment by goliatone** [comment]
@miqmago I needed something quickly so ended up using a [different library](https://github.com/apache/cordova-plugin-network-information), which seems to be working fine.

**Comment by maa105** [comment]
nothing is working :( this plugin had great potential. none on the market does what it does. too bad it was left like this. the onReachabilityChanged never gets called niether do the success or error functions passed to observeRemote[...] functions. hope it gets resolved soon

**Comment by miqmago** [comment]
As @goliatone said, there is an official plugin from cordova, so this one will no longer be maintained. Please use official one, which does mostly the same
